import { SpecInput } from "./calculator";

export interface MachinePreset {
  id: string;
  label: string;
  sourceUrl: string;
  input: SpecInput;
}

const yutimeOff = {
  enabled: false,
  triggerSpins: 999,
  supportSpins: 900,
  probabilityMode: "normal" as const,
  highProbability: 99,
};

const noTimeShort = { enabled: false, spins: 100 };

export const MACHINE_PRESETS: MachinePreset[] = [
  {
    id: "eva15",
    label: "Pエヴァ15",
    sourceUrl: "https://p-town.dmm.com/machines/4021",
    input: {
      name: "P新世紀エヴァンゲリオン15 未来への咆哮",
      machineType: "P",
      regulationType: "classic",
      rushMode: "standard",
      hitProbability: 319,
      rushEntryRate: 59,
      rushContinuationRate: 81,
      upperRushEntryRate: 0,
      upperRushContinuationRate: 81,
      ltContinuationRate: 81,
      continuationCalcMode: "st",
      rightHitProbability: 99,
      rushStSpins: 163,
      upperRushStSpins: 163,
      ltStSpins: 163,
      nonRushTimeShort: { enabled: true, spins: 100 },
      initialPayout: 450,
      payoutTiers: [
        { id: "eva15-1500", label: "10R", payout: 1500, rate: 100, bonusCount: 1 },
      ],
      yutime: yutimeOff,
      benchmark: {
        sourceLabel: "DMMぱちタウン",
        sourceUrl: "https://p-town.dmm.com/machines/4021",
        avgTotalPayoutBalls: 4498,
        borderSpins4Yen: 17.8,
        conditionNote: "電サポ中の出玉増減-10%、通常時2000回転（10時間）から算出。",
      },
    },
  },
  {
    id: "tokyo-ghoul",
    label: "e東京喰種W",
    sourceUrl: "https://p-town.dmm.com/machines/4782",
    input: {
      name: "e東京喰種W",
      machineType: "e",
      regulationType: "lt",
      rushMode: "directLt",
      hitProbability: 399,
      rushEntryRate: 51,
      rushContinuationRate: 75,
      upperRushEntryRate: 100,
      upperRushContinuationRate: 75,
      ltContinuationRate: 75,
      continuationCalcMode: "st",
      rightHitProbability: 95,
      rushStSpins: 130,
      upperRushStSpins: 130,
      ltStSpins: 130,
      nonRushTimeShort: noTimeShort,
      initialPayout: 1500,
      payoutTiers: [
        { id: "ghoul-3000", label: "10R x2", payout: 3000, rate: 94, bonusCount: 2 },
        { id: "ghoul-6000", label: "10R x4", payout: 6000, rate: 6, bonusCount: 4 },
      ],
      yutime: yutimeOff,
      benchmark: {
        sourceLabel: "DMMぱちタウン",
        sourceUrl: "https://p-town.dmm.com/machines/4782",
        avgTotalPayoutBalls: 2998,
        borderSpins4Yen: 16.7,
        conditionNote: "電サポ中の出玉増減-5%、通常時2000回転（10時間）から算出。",
      },
    },
  },
  {
    id: "eva17",
    label: "eエヴァ17",
    sourceUrl: "https://p-town.dmm.com/machines/4894",
    input: {
      name: "e新世紀エヴァンゲリオン17 はじまりの記憶R",
      machineType: "e",
      regulationType: "lt",
      rushMode: "directLt",
      hitProbability: 399,
      rushEntryRate: 61,
      rushContinuationRate: 80,
      upperRushEntryRate: 100,
      upperRushContinuationRate: 80,
      ltContinuationRate: 80,
      continuationCalcMode: "st",
      rightHitProbability: 99,
      rushStSpins: 157,
      upperRushStSpins: 157,
      ltStSpins: 157,
      nonRushTimeShort: { enabled: true, spins: 100 },
      initialPayout: 1500,
      payoutTiers: [
        { id: "eva17-2400", label: "8R x2", payout: 2400, rate: 100, bonusCount: 2 },
      ],
      yutime: yutimeOff,
      benchmark: {
        sourceLabel: "DMMぱちタウン",
        sourceUrl: "https://p-town.dmm.com/machines/4894",
        avgTotalPayoutBalls: 5987,
        borderSpins4Yen: 16.7,
        conditionNote: "電サポ中の出玉増減-5%、通常時2000回転（10時間）から算出。",
      },
    },
  },
  {
    id: "rezero2",
    label: "eリゼロ2",
    sourceUrl: "https://p-town.dmm.com/machines/4457",
    input: {
      name: "e Re:ゼロから始める異世界生活 season2M13",
      machineType: "e",
      regulationType: "classic",
      rushMode: "standard",
      hitProbability: 349,
      rushEntryRate: 55,
      rushContinuationRate: 77,
      upperRushEntryRate: 0,
      upperRushContinuationRate: 77,
      ltContinuationRate: 77,
      continuationCalcMode: "st",
      rightHitProbability: 99,
      rushStSpins: 145,
      upperRushStSpins: 145,
      ltStSpins: 145,
      nonRushTimeShort: noTimeShort,
      initialPayout: 1500,
      payoutTiers: [
        { id: "rezero-1500", label: "10R", payout: 1500, rate: 75, bonusCount: 1 },
        { id: "rezero-3000", label: "10R x2", payout: 3000, rate: 25, bonusCount: 2 },
      ],
      yutime: yutimeOff,
      benchmark: {
        sourceLabel: "DMMぱちタウン",
        sourceUrl: "https://p-town.dmm.com/machines/4457",
        avgTotalPayoutBalls: 5282,
        borderSpins4Yen: 16.6,
        conditionNote: "電サポ中の出玉増減-5%、通常時2000回転（10時間）から算出。",
      },
    },
  },
  {
    id: "karakuri2",
    label: "eからくり2",
    sourceUrl: "https://p-town.dmm.com/machines/4649",
    input: {
      name: "eフィーバーからくりサーカス2R",
      machineType: "e",
      regulationType: "lt",
      rushMode: "directLt",
      hitProbability: 399,
      rushEntryRate: 52,
      rushContinuationRate: 80,
      upperRushEntryRate: 100,
      upperRushContinuationRate: 80,
      ltContinuationRate: 80,
      continuationCalcMode: "rate",
      rightHitProbability: 78,
      rushStSpins: 135,
      upperRushStSpins: 135,
      ltStSpins: 135,
      nonRushTimeShort: noTimeShort,
      initialPayout: 300,
      payoutTiers: [
        { id: "karakuri-reset", label: "STリセット", payout: 0, rate: 18, bonusCount: 1 },
        { id: "karakuri-1500", label: "10R", payout: 1500, rate: 62, bonusCount: 1 },
        { id: "karakuri-3000", label: "10R x2", payout: 3000, rate: 15, bonusCount: 2 },
        { id: "karakuri-4500", label: "10R x3", payout: 4500, rate: 4, bonusCount: 3 },
        { id: "karakuri-7500", label: "10R x5", payout: 7500, rate: 1, bonusCount: 5 },
      ],
      yutime: yutimeOff,
      benchmark: {
        sourceLabel: "DMMぱちタウン",
        sourceUrl: "https://p-town.dmm.com/machines/4649",
        avgTotalPayoutBalls: 5552,
        borderSpins4Yen: 18.1,
        conditionNote: "電サポ中の出玉増減なし、通常時2000回転（10時間）から算出。",
      },
    },
  },
  {
    id: "gensan2",
    label: "P源さん超韋駄天2",
    sourceUrl: "https://p-town.dmm.com/machines/4532",
    input: {
      name: "P大工の源さん超韋駄天2HLB",
      machineType: "P",
      regulationType: "lt",
      rushMode: "twoStage",
      hitProbability: 129,
      rushEntryRate: 56,
      rushContinuationRate: 88,
      upperRushEntryRate: 25,
      upperRushContinuationRate: 96,
      ltContinuationRate: 96,
      continuationCalcMode: "rate",
      rightHitProbability: 2,
      rushStSpins: 3,
      upperRushStSpins: 6,
      ltStSpins: 6,
      nonRushTimeShort: noTimeShort,
      initialPayout: 240,
      payoutTiers: [
        { id: "gensan-240", label: "3R", payout: 240, rate: 75, bonusCount: 1 },
        { id: "gensan-720", label: "9R", payout: 720, rate: 25, bonusCount: 1 },
      ],
      yutime: yutimeOff,
      benchmark: {
        sourceLabel: "DMMぱちタウン",
        sourceUrl: "https://p-town.dmm.com/machines/4532",
        avgTotalPayoutBalls: 1823,
        borderSpins4Yen: 17.8,
        conditionNote: "電サポ中の出玉増減なし、通常時2000回転（10時間）から算出。",
      },
    },
  },
];
